### ISSUE TITLE
npx jetify never ends

### ISSUE THREAD

**Issue by fgagneten** [mikehardy/jetifier#40] opened 2019-07-22 22:24 UTC
after a yarn command, I execute on postInstall
    npx jetify

I get no errors but npx never ends! After waiting 10 minutes I had to cut it. No error or logs:
![image](https://user-images.githubusercontent.com/14353978/61669375-3b465080-acb6-11e9-81ec-a709499a7888.png)

I have installed npx globally.

What am I doing wrong?

Thanks

**Comment by mikehardy** [comment] 2019-07-23 02:39
This is odd - I've seen the CLI hang on other things as well. My first take on this is that jetify is powerful, but in the end pretty simple and I don't think it's at fault. I'll leave this open pending any investigation others want to do but the quick+easy workaround is to instead call it as `./node_modules/.bin/jetify`

**Comment by fgagneten** [comment] 2019-07-27 18:37
Same, is like Jetify never executes. On windows works like a charm

**Comment by mikehardy** [comment] 2019-07-28 14:02
on mac and linux works like a charm for me as well. it's integrated in the main react-native-community/cli now so everyone using RN60+ is running it every time by default now, indicating (to me) that it's working mostly. There must be some edge-case combo of versions so in order to troubleshoot we'd likely need a full repo that reproduces it including specification of all the versions involved.

**Comment by GonzaloRecioG** [comment] 2019-08-12 14:40
Same thing as @fgagneten , either with `react-native run-android` , `npx jetify` or `npx ./node_modules/.bin/jetify`, it never ends and doesn't give you any output.

**Comment by mikehardy** [comment] 2019-08-12 14:49
"Same thing" is not that useful, I need exact versions of everything in play (OS, node, react-native, jetifier etc). Imagine you wanted to reproduce it, what would you need to know to set up a reproduction and reproduce? I need that...

**Comment by mikehardy** [comment] 2019-08-12 14:51
Also worth noting that if you have installed the jetifier package, just running `./node_modules/.bin/jetify` should work (no need for npx)

**Comment by kyken** [comment] 2019-08-15 23:57
I have same situation.
In my case, it was too many libraries below `node_modules` to scan.
I patched `index.js` to search specific directories and fixed.

**Comment by mikehardy** [comment] 2019-08-16 02:07
interesting - wouldn't that eventually finish, but just be slow? or run out of file handles? odd that it just hangs

**Comment by kyken** [comment] 2019-08-16 04:34
simply, just be slow.
I experimented adding debug code (just console.log) to util.js -> readDir function and `npx jetify` for 30 minutes.
stdout kept outputting.
So I thought it would be better to modify to scan only certain libraries(from package.json or build.gradle...).

**Comment by Rendfold** [comment] 2019-08-20 22:55
With using symlinks it actually gets stuck, even if there is only one dependency.

**Comment by mikehardy** [comment] 2019-08-20 23:36
@Rendfold now that is potentially reproducible! I'd love for there to be some sort of glob argument that allowed what to jetify as long as the current behavior stayed as is

**Comment by Rendfold** [comment] 2019-08-23 19:23
@mikehardy what about an array of paths, which needs to be jetified? While by default it will jetify whole node_modules, as it does now (I think).
I'm using lerna, by the way. And by deleting symlinks, or specifying some paths it did actually work!
I would like to help with implementing the feature I mentioned above, but I'm still newbie to open source projects and contributing.

**Comment by mikehardy** [comment] 2019-08-23 20:06
Hey @Rendfold! An array of paths sounds fine as a start - I wouldn't mind that personally. I will say that it seems globs/patterns must be easy since all the other configs do it, maybe there is a good example in @react-native-community/cli or jest etc to just reference. 

As for open source projects and contributing, I'd say fork the repo, clone it locally to get it working, and make a branch for the new feature. Get it working there and after you push that branch back to your fork, github will suggest you make a PR for it - do that and we can get it merged once it looks good.

If you want earlier collaboration feel free to push it earlier and make a PR that starts with WIP and we can give it a look

**Comment by mikehardy** [comment] 2019-08-25 17:07
here's something - https://github.com/isaacs/node-glob - also should be cross-linked with #39 because if you could specify a glob (or array of globs) then you could workaround whatever problem there is

**Comment by OleksandrKucherenko** [comment] 2019-08-26 12:15
https://github.com/mikehardy/jetifier/pull/50 - this PR can help to understand what is going on... `--verbose` flag added

**Comment by adrianha** [comment] 2019-10-30 06:40
i was facing this issue also, already tried to run `npx jetify` or `./node_modules/.bin/jetify` but it is still not running.
What's working for me is to run this command: `git clean -fdx` to clean untracked git files from directory. After running that command, jetify can works normally

**Comment by Andrew-Lomakin** [comment] 2019-11-15 19:33
I had the same problem, on the latest version.
I saw an error on version 1.5.1:
`yarn add jetifier@1.5.1 `
`npx jetify`
I saw by the log that it complains about _react-native-http/example_
`rm -rf ./node_modules/react-native-http/example`
Success!

**Comment by gaodeng** [comment] 2019-11-28 14:07
> I had the same problem, on the latest version.
> I saw an error on version 1.5.1:
> `yarn add jetifier@1.5.1 `
> `npx jetify`
> I saw by the log that it complains about _react-native-http/example_
> `rm -rf ./node_modules/react-native-http/example`
> Success!

related https://github.com/mikehardy/jetifier/issues/55

**Comment by mikehardy** [comment] 2022-01-19 14:05
We should all be using `--no-jetifier` in our builds (I am, successfully) at this point, and this repo should be sunset, I don't expect to make further changes in it

**Closed by mikehardy** 2022-01-19 14:05 UTC
Labels: needs reproduction, requested user feedback
